settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  # Data ETL & Feature engineering pipelines parameters
  # This is YOUR twin. Add your own name(s) and the links to your writing.
  author_links:
    - user_full_name: Jerry # [First Name(s)] [Last Name]
      links: []
        # Example:
        # - https://medium.com/@your-handle/your-article
        # - https://your-name.substack.com/p/your-post
  # Generate instruct dataset pipeline parameters
  test_split_size: 0.1
  push_to_huggingface: false
  dataset_id: your-hf-username/llmtwin
  mock: false
