settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  # This is YOUR twin. List the author name(s) whose crawled content to process.
  author_full_names:
    - Jerry # [First Name(s)] [Last Name]
